#!/usr/bin/env zsh

# AWS Functions
function aws_assume_role() {
    export AWS_PROFILE="$1"
    if [ -z "$2" ]; then
        KOPS_STATE_STORE="$KOPS_STATE_STORE"
    else
        echo "Storing previous KOPS_STATE_STORE: $KOPS_STATE_STORE"
        export PREV_KOPS_STATE_STORE="$KOPS_STATE_STORE"
        KOPS_STATE_STORE="$2"
    fi
    echo "Assuming into role..."
    ROLE_ARN=$(aws configure get role_arn --profile $AWS_PROFILE)
    ROLE_JSON=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name $(whoami)-$AWS_PROFILE)
    export AWS_ACCESS_KEY_ID="$(echo $ROLE_JSON | jq -r ".Credentials.AccessKeyId")"
    export AWS_SECRET_ACCESS_KEY="$(echo $ROLE_JSON | jq -r ".Credentials.SecretAccessKey")"
    export AWS_SESSION_TOKEN="$(echo $ROLE_JSON | jq -r ".Credentials.SessionToken")"
    export AWS_SDK_LOAD_CONFIG='true'
    export AWS_REGION="us-east-1"
    export KOPS_STATE_STORE="$KOPS_STATE_STORE"
}

function aws_assume_role_long() {
    export AWS_PROFILE="cibo-no-mfa"
    local MFA_CREDENTIALS_FILE="$HOME/.aws/mfa/serial"
    local MFA_SERIAL_NUMBER="$(jq -cr '.MFADevices[0].SerialNumber' $MFA_CREDENTIALS_FILE)"
    local AWS_PROD_ROLE="$1"
    echo "Allowing maximum time of 43200 seconds aka 12 hours"
    local DURATION_SECONDS=43200
    ROLE_ARN=$(aws configure get role_arn --profile $AWS_PROD_ROLE)
    printf "MFA Code: "
    read TOKEN_CODE
    ROLE_JSON=$(aws sts assume-role --role-arn $ROLE_ARN --role-session-name $(whoami)-$AWS_PROD_ROLE --duration-seconds $DURATION_SECONDS --serial-number $MFA_SERIAL_NUMBER --token-code $TOKEN_CODE)
    export AWS_ACCESS_KEY_ID="$(echo $ROLE_JSON | jq -r ".Credentials.AccessKeyId")"
    export AWS_SECRET_ACCESS_KEY="$(echo $ROLE_JSON | jq -r ".Credentials.SecretAccessKey")"
    export AWS_SESSION_TOKEN="$(echo $ROLE_JSON | jq -r ".Credentials.SessionToken")"
    EXPIRATION_DATE=$(echo $ROLE_JSON | jq -r ".Credentials.Expiration")
    echo "Verify expiration date in UTC time is 12 hours from now"
    echo "Expiration date: $EXPIRATION_DATE"
    echo "Current date   : $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    export AWS_SDK_LOAD_CONFIG="true"
    export AWS_REGION="us-east-1"
}

function aws_check_role() {
    echo "AWS_PROFILE: $AWS_PROFILE"
    echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
    echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
    echo "AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN"
    echo "AWS_SDK_LOAD_CONFIG: $AWS_SDK_LOAD_CONFIG"
    echo "AWS_REGION: $AWS_REGION"
    echo "KOPS_STATE_STORE: $KOPS_STATE_STORE"
}

function aws_unassume_role_long() {
    unset AWS_PROFILE
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN
    unset AWS_SDK_LOAD_CONFIG
    unset AWS_REGION
}

function aws_unassume_role() {
    if [ -z "$PREV_KOPS_STATE_STORE" ]; then
        echo "It already is the same, don't do anything" >&2
    else
        echo "It exists, return to normal. Original: $PREV_KOPS_STATE_STORE" >&2
        export KOPS_STATE_STORE="$PREV_KOPS_STATE_STORE"
    fi
    unset AWS_PROFILE
    unset AWS_ACCESS_KEY_ID
    unset AWS_SECRET_ACCESS_KEY
    unset AWS_SESSION_TOKEN
    unset AWS_SDK_LOAD_CONFIG
    unset AWS_REGION
}

function aws_assume_sdk_load() {
    AWS_PROFILE="$1"
    if [ -z "$2" ]; then
        export KOPS_STATE_STORE="$KOPS_STATE_STORE"
    else
        echo "Storing previous KOPS_STATE_STORE: $KOPS_STATE_STORE"
        export PREV_KOPS_STATE_STORE="$KOPS_STATE_STORE"
        KOPS_STATE_STORE="$2"
    fi
    export AWS_PROFILE="$AWS_PROFILE"
    export AWS_SDK_LOAD_CONFIG='true'
    export AWS_REGION="us-east-1"
    export KOPS_STATE_STORE="$KOPS_STATE_STORE"
}

function aws_check_sdk() {
    echo "AWS_PROFILE: $AWS_PROFILE"
    echo "AWS_SDK_LOAD_CONFIG: $AWS_SDK_LOAD_CONFIG"
    echo "AWS_REGION: $AWS_REGION"
    echo "KOPS_STATE_STORE: $KOPS_STATE_STORE"
}

function aws_unassume_sdk_load() {
    if [ -z "$PREV_KOPS_STATE_STORE" ]; then
        echo "It already is the same, don't do anything"
    else
        export KOPS_STATE_STORE="$PREV_KOPS_STATE_STORE"
    fi
    unset AWS_PROFILE
    unset AWS_SDK_LOAD_CONFIG
    unset AWS_REGION
}
