#!/usr/bin/env zsh

### FUNCTIONS ###

case "$OSTYPE" in
    darwin*)
        alias ll='eza -lah'
        # Function to call IntelliJ Idea from command line at directory and passing all possible parameters
        function idea {
            open -a /Applications/IntelliJ\ Idea\ CE.app/Contents/MacOS/idea $@
        }
        # Function clear emacs Darwin
        function osx_clear_emacs () {
            rm /usr/local/bin/emacs*
            rm /usr/local/bin/etags
            rm /usr/local/bin/ebrowse
        }
        # terraform sed for fun and profit
        function format_plan {
            awk '
    /Terraform will perform the following actions:/ { found=1 }
    /------------------------------------------------------------------------/ { found=0 }
    // { if (found) { print $0 } }
  ' $1 |
                (
                    printf '<details>\n<summary>Plan for %s</summary>\n\n```diff\n' "$2" &&
                        perl -pe 's/\x1b\[[0-9;]*[mG]//g' |
                            sed -e 's/^\(  *\)\([\+-]\)/\2\1/' -e 's/^\(  *\)~/!\1/' &&
                        printf '```\n</details>'
                ) | pbcopy
        }
        ;;
    linux*)
        function format_plan {
            awk '
     /Terraform will perform the following actions:/ { found=1 }
     /------------------------------------------------------------------------/ { found=0 }
     // { if (found) { print $0 } }
   ' $1 |
                (
                    printf '<details>\n<summary>Plan for %s</summary>\n\n```diff\n' "$2" &&
                        perl -pe 's/\x1b\[[0-9;]*[mG]//g' |
                            sed -e 's/^\(  *\)\([\+-]\)/\2\1/' -e 's/^\(  *\)~/!\1/' &&
                        printf '```\n</details>'
                ) | xclip -selection clipboard
        }
esac

# Function to clear all metals and bloop remnants
function clear_metals () {
    if [[ -a "build.sbt" ]]; then
        find . -name "*metals*" | xargs -I {} rm -rf {} \;
        find . -name "*bloop*" | xargs -I {} rm -rf {} \;
    else
        echo "Not at the root of an SBT project"
        return 1
    fi
}

# DGD Function for git page
function ghp () {
    repo="https://"`git config --get remote.origin.url | sed 's|git@||' | sed 's|\.git||' | sed 's|:|/|'`
    case "$OSTYPE" in
        darwin*)
            open "$repo/pulls"
            ;;
        linux*)
            xdg-open "$repo/pulls"
            ;;
    esac
}

function git_empty_commit() {
    git commit --allow-empty -m "Empty-Commit"
}

function fpathClean() {
    # Cleans fpath of duplicated portions
    NEWPATH=$(echo $1 | sed -e 's/ /\'$'\n/g' | perl -ne 'print unless $seen{$_}++' | paste -s -d' ' -)
    echo $NEWPATH
}

function start_agent {
    echo "Initialising new SSH agent..."
    /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    echo succeeded
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
    /usr/bin/ssh-add;
}

# Path Manipulation
function pathClean() {
    # Cleans path of duplicated portions.
    NEWPATH=$(echo $1 | sed 's/:/\'$'\n/g' | perl -ne 'print unless $seen{$_}++' | paste -s -d':' -)
    echo "$NEWPATH"
}

function terraform_admin () {
    export USE_GITHUB_OAUTH_TOKEN=k8s
    ./terraform "$@"
}
